#!/bin/sh

# run a screen based on the host name - useful with multiple logins
# where home directory is shared.

# Since screen will invoke a login shell, clear the path first on a mac
# (otherwise /usr/libexec/path_helper ends up doubling the path)
if test -f /usr/libexec/path_helper; then
    PATH=
fi

exec /usr/bin/screen -DR `/bin/hostname -s` "$@"
