#!/bin/bash 
export PATH=$PATH:/usr/local/bin
#echo "$$ $PPID"
#ps lwwwwp $$,$PPID
#set 

# abort if we're already inside a TMUX session
[ "$TMUX" == "" ] || exit 0 

# startup a "default" session if none currently exists
# we call ours "main"
tmux has-session -t main &>/dev/null || tmux new-session -s main -d 

# present menu for user to choose which workspace to open
PS3="Please choose your session: "
options=($(tmux list-sessions -F "#S") "NEW SESSION" "BASH")
echo "Available sessions"
echo "------------------"
echo " "
select opt in "${options[@]}"
do
    case $opt in
        "NEW SESSION")
            read -p "Enter new session name: " SESSION_NAME
            exec tmux new -s "$SESSION_NAME"
            break
            ;;
        "BASH")
            bash --login
            break;;
        *) 
            exec tmux attach-session -t $opt 
            break
            ;; 
    esac
done
