#!/usr/bin/env python

"""
    Pull fresh r/o copies of keepass databases
"""

import argparse
import logging
import os
import sh

sftp = sh.sftp.bake('-p')
scp = sh.scp.bake('-p')

logger = logging.getLogger(__name__)
logger = logging.getLogger(__name__)


kdb_files = {
    "~/Personal.kdb": '''"Dropbox/Hal's Stuff/Personal.kdb"''',
    "~/Homeinfo.kdb": "Dropbox/home/Homeinfo.kdb",
}


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--backup", help='backup files',
                        action='store_true')
    return parser.parse_args()


def main():
    args = parse_args()
    for here, there in kdb_files.items():
        here = os.path.expanduser(here)
        if not os.path.exists(here):
            logger.warning("Missing local file '%s'", here)
            continue
        try:
            if args.backup:
                scp('{}'.format(here), 'hal@home:{}'.format(there))
                logger.info("backedup {}".format(here))
            else:
                os.chdir(os.path.dirname(here))
                sftp('hal@home:{}'.format(there))
                logger.info("updated {}".format(here))
        except Exception as e:
            logger.error('failed to update %s because %s', here, e)


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s')
    main()
