#!bash
if ! type -p git &>/dev/null && test -x /usr/local/git/bin/git ; then
    PATH=$PATH:/usr/local/git/bin
fi
if type -p git &>/dev/null; then
    GIT_COMPLETION_FILE=/usr/local/git/contrib/completion/git-completion.bash
    if test -f $GIT_COMPLETION_FILE; then
        source $GIT_COMPLETION_FILE
    fi
    unset GIT_COMPLETION_FILE
else
    echo "'git' not on path, not sourcing completion"
fi
