#!/bin/bash

# script to go through all swp files after a system crash

base_dir=(
    '/Users/hwine/gd/workwiki'
    )

function _get_original() {
    local swap_name="$1"
    local orig_name=${swap_name%.swp}
    orig_name=${orig_name#.}
    echo $orig_name
}

function _process_dir() {
    local dir="$1"
    for f in $(find $dir -name \.\*.swp) ; do
        local f_path=$(dirname $f)
        local f_swp_base=$(basename $f)
        local f_main=$(_get_original $f_swp_base)
        echo "Fixing $f_main"
        vim $f_path/$f_main
    done
}

if test $# -eq 0; then
    set "${base_dir[@]}"
fi

for dir; do
    echo "Checking: $dir"
    _process_dir "$dir"
done
